### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by pjfichet** [nstockton/mapperproxy-mume#33]
Hey Nick,

I just updated mume-mapperproxy, and everything was working for a few hours, until it hit a unicode decode error. Now, it crashes on login with the same error.

I don't remember doing anything special, excepting experimenting with "change width all ..."

Here is the error log:
```python
Exception in thread Game:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/pj/doc/src/mapperproxy-mume/src/mapper/main.py", line 89, in run
    self.mapper.proxy.game.parse(data)
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/manager.py", line 127, in parse
    self._handlers[0].on_dataReceived(data)
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/mccp.py", line 57, in on_dataReceived
    super().on_dataReceived(self._decompressor.decompress(inputBuffer))
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/telnet.py", line 460, in on_dataReceived
    super().on_dataReceived(bytes(appDataBuffer))
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/base.py", line 85, in on_dataReceived
    self._receiver(data)
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/mpi.py", line 210, in on_dataReceived
    super().on_dataReceived(bytes(appDataBuffer))
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/base.py", line 85, in on_dataReceived
    self._receiver(data)
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/xml.py", line 223, in on_dataReceived
    data = self._handleXMLTag(data, appDataBuffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pj/doc/src/mapperproxy-mume/.venv/lib/python3.11/site-packages/mudproto/xml.py", line 166, in _handleXMLTag
    tagName: str = str(tag, "us-ascii").strip("/").split(None, 1)[0] if tag else ""
                   ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
```

I wish you a good day !

**Comment by pjfichet** [comment]
Hello Again !

So, setting "change encoding ascii" within mume fixed it.

**Comment by nstockton** [comment]
Should be fixed now. Do a ```git pull``` from master, then ```poetry install``` to update the mud-protocols dependency. Let me know if it works for you.
Also, out of curiosity, how were you able to change the character set? By default, the code is set to invisibly negotiate US-ASCII using the telnet charset negotiation, and once negotiated, the MUME server should have prevented you from changing it. I can look in to changing the code so that a different character set can be used, but was curious how you managed to set it to something other than US-ASCII.

**Comment by pjfichet** [comment]
I'm using tintin++ `#config {charset} {utf-8}`, which does its own telnet negotiation. It's configured as is for some years, and was probably prevented by mmapper, until something changed somewhere...

I'm testing your change during the day,
Thank you !

**Comment by pjfichet** [comment]
I updated, tested, and it works perfectly now.

I'm still using `#config {charset} {utf-8}` on tintin++, and within mume, `change encoding` reports `utf-8`. Please, tell me if I should better use ascii.

Thank you !

**Comment by nstockton** [comment]
Glad it is now working for you. Changing charset via your client should work fine now. I made some more improvements on the mud-protocols side, so you might want to do a ```git pull``` and ```poetry install``` to get them.
Current behavior is mapper will enable telnet charset negotiation and initially negotiate US-ASCII. The player can then forcibly change the charset in the client to another charset supported by MUME, as you are doing with your TinTin command. Internally, mapper converts everything to US-ASCII for string comparison, mapper commands (flabel/fname/ETC), and map storage. The player should still receive text from MUME unmodified, in the desired encoding.
I have some ideas on how this can be further improved, but don't have time to work on it at the moment. I'm currently working on moving to a new place, but charset support is something I would like to improve in the future.
